### PR TITLE
Task 9 (Backend For Frontend)

### PR DESCRIPTION
**Pull request by tsialiukigor**
**Task 9 (Backend For Frontend)**

BFF-SERVICE links:
- http://bff-service.eu-west-1.elasticbeanstalk.com/products ---------> original: https://a7uftfm800.execute-api.eu-west-1.amazonaws.com/dev/products
- http://bff-service.eu-west-1.elasticbeanstalk.com/cart -------> original: http://cart-api-service-dev.eu-west-1.elasticbeanstalk.com/api/cart

FE link:
- http://d2w2h6xfwejks9.cloudfront.net/

Everything is done;

Estimated score: **7**

### CODE REVIEW

**Comment by skyRoma** [comment]
Response data is not the same: 

image

image

For **Cart** API also

**Comment by skyRoma** [comment]
Please, provide all required data: 
image

**Review by skyRoma — APPROVED** [review]

**Comment by KarneyenkaDzmitry** [comment]
The Bff-service returns 
statusCode and message as additional to origin data array for products in a body. Expected the same behavior. 
image

Please, let me know once you fix it and I will update a grade in RSS-App

**Comment by tsialiukigor** [comment]
> Response data is not the same:
> 
> image
> 
> image
> 
> For **Cart** API also

Yes, sorry, I didn't pay attention to this. I've already updated! Thanks

**Comment by tsialiukigor** [comment]
> The Bff-service returns
> statusCode and message as additional to origin data array for products in a body. Expected the same behavior.
> image
> 
> Please, let me know once you fix it and I will update a grade in RSS-App

Yes, sorry, I didn't pay attention to this. I've already updated! Thanks

**Comment by tsialiukigor** [comment]
> Please, provide all required data:
> image

link to repo: https://github.com/sijlver/nodejs-aws-backend/pull/7
product-service service API endpoint URL: http://bff-service.eu-west-1.elasticbeanstalk.com/products ---------> original: https://a7uftfm800.execute-api.eu-west-1.amazonaws.com/dev/products
example of the create product API call with all needed information: URL, payload, headers, etc.:
navigate to http://d2w2h6xfwejks9.cloudfront.net/
press 
image
press 
image
here yoy are 
image
The same flow as everone should have
CART service API endpoint URL: 
http://bff-service.eu-west-1.elasticbeanstalk.com/cart -------> original: http://cart-api-service-dev.eu-west-1.elasticbeanstalk.com/api/cart
bff-service service URL: http://bff-service.eu-west-1.elasticbeanstalk.com
example how to call product-service and CART services via bff-service service URL: http://bff-service.eu-west-1.elasticbeanstalk.com/cart -------> original: http://cart-api-service-dev.eu-west-1.elasticbeanstalk.com/api/cart
http://bff-service.eu-west-1.elasticbeanstalk.com/products ---------> original: https://a7uftfm800.execute-api.eu-west-1.amazonaws.com/dev/products

**Pull request merged**
